### ISSUE TITLE
feat: create env in Dockerfile & Docker-Compose

### ISSUE THREAD

**Issue by SantiagoGaonaC** [hawks-atlanta/proxy-net#22]
```
ENV ASPNETCORE_URLS=$ASPNETCORE_URLS
ENV SERVICE_URL=$SERVICE_URL
```
```

Docker Compose:
  # Proxy-net
  # Local/Docker http://gateway:8080/service
  # Remote       http://URL/service
  proxy-net:
    container_name: proxy-net
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
      - SERVICE_URL=http://gateway:8080/service # NO ADD ?WSDL! | connect to Localhost with using name "gateway" container
```
